# Generated by Django 4.2.1 on 2023-05-17 13:33

import appmmo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmmo', '0003_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, height_field=100, max_length=255, null=True, upload_to=appmmo.models.user_directory_path, width_field=100),
        ),
    ]
