# Generated by Django 4.2.1 on 2023-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmmo', '0005_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='text',
            field=models.TextField(help_text='Поле отклика'),
        ),
    ]
