# Generated by Django 4.2.1 on 2023-05-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmmo', '0006_alter_responses_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='is_activited',
            field=models.BooleanField(default=False),
        ),
    ]
