# Generated by Django 4.2.1 on 2023-05-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmmo', '0007_responses_is_activited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='is_activited',
            new_name='is_active',
        ),
    ]
